services:
  ems-app:
    build: .
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s